package gui;

public enum CrtOpcija {
	DEFAULT, TACKA, LINIJA, KVADRAT, PRAVOUGAONIK,
	KRUG, CETKA, SELEKTUJ, MODIFIKUJ, OBRISI, 
	POMERI, OBRISI_SVE, UNDO, REDO,
	DRGKVADRAT, DRGKRUG, DRGPRAVOUGAONIK, DRGLINIJA, KANTICA, PIPETA;
}
